### ISSUE TITLE
INKawa

### ISSUE THREAD

**Issue by S11verWolf** [Buer-Nahida/check#1]
# 你的网站链接
space.bilibili.com/405549514

# 介绍
我是银狼。我的游戏账号被封禁了，所以我正在制裁黑塔小人。如果你关注了我的bilibili，我会把黑塔的照片发给你。

# 封面
![Image_1723356674728](https://github.com/user-attachments/assets/3b22c773-88b4-4fa6-aff8-a8092a527ba3)

**Comment by Buer-Nahida** [comment]
加好了
