### ISSUE TITLE
[New Friend] VacuolePao

### ISSUE THREAD

**Issue by VacuolePaoo** [Buer-Nahida/check#2]
# 你的网站链接 vacuole.top

# 介绍 哥们啥实力啊，要不要来逛绳网[doge]

# 封面 用Gayhub头像吧

**Comment by Buer-Nahida** [comment]
[doge]是要转换为B站的![doge](https://i0.hdslb.com/bfs/emote/3087d273a78ccaff4bb1e9972e2ba2a7583c9f11.png@40w_40h.avif)还是保持原样？

**Comment by Buer-Nahida** [comment]
加好了
